### ISSUE TITLE
Pesticide can enable more animals!

### ISSUE THREAD

**Issue by barryokane** [HappyPorch/Go-Diverse#1]
To recreate : https://www.loom.com/share/da062ed0c11c4a0ea5d465664f72d14b

1. Click on all right hand features
2. Click on pesticide
3. Wait till animals die
4. Click on barn again (to get owl back)
5. Click on pesticide again == you now get all the animals coming back!

**Comment by tomvanenckevort-hp** [comment]
Fixed in https://github.com/HappyPorch/Go-Diverse/commit/ef25fdc3b3c669a8bef59660b2cfc3beb722d5d9
